ci: add information to the rustfmt check, hinting at the necessary fix (#2673)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -184,7 +184,11 @@ jobs:
       # Check fmt
       - name: "rustfmt --check"
         # Workaround for rust-lang/cargo#7732
-        run: rustfmt --check --edition 2018 $(find . -name '*.rs' -print)
+        run: |
+          if ! rustfmt --check --edition 2018 $(find . -name '*.rs' -print); then
+            printf "Please run \`rustfmt --edition 2018 \$(find . -name '*.rs' -print)\` to fix rustfmt errors.\nSee CONTRIBUTING.md for more details.\n" >&2
+            exit 1
+          fi
 
   clippy:
     name: clippy
